export class HjbxxModel {
    id: string;        //物理键id';
    ssxtdm: string;        //所属系统代码';
    ssgcdm: string;        //所属工程代码';
    jddm: string;        //阶段代码';
    ssxzqhdm: string;        //所属行政区划代码';
    xzqhmc: string;        //所属行政区划代码';
    zydldm: string;        //专业大类代码';
    zydlmc: string;
    dcfwdm: string;        //调查范围代码';
    dcfwmc: string;
    hlbdm: string;        //户类型代码';
    hlbmc: string;        //户类型代码';
    hzxm: string;        //户主姓名';
    dabh: string;        //档案编号';
    hs: string;        //户数';
    sfkgh: string;        //是否空挂户';
    sfxw: number;        //是否线外';
    dclsh: string;        //调查流水号';
    szzdgc: string;        //所在最低高程';
    szzggc: string;        //所在最高高程';
    dmbh: string;        //断面编号';
    sfcx: string;        //是否撤销';
    cxsj: string;        //撤销时间';
    cxyy: string;        //撤销原因';
    sfxh: string;        //是否销户';
    xhsj: string;        //销户时间';
    bz: string;        //备注';
    cjsj: string;        //创建时间';
    zhgxsj: string;        //最后更新时间';
}
